### ISSUE TITLE
Keyboard Layout for Razer Blade stealth, doesn't allow you to select all the keys.

### ISSUE THREAD

**Issue by hhollenstain** [polychromatic/polychromatic#11]
I was able to map most of the keys using the layout on my RBS but the F1 Key, the left arrow, enter, and z keys can't be mapped from the UI. Not surprised because this tool is designed for the full sized keyboard layout. This would be possibly a great new feature to be able to select the layout when making a custom key mapping layout.

**Comment by terrycain** [comment]
Might be something to do with the mapping dictionary. I'll have a look Friday.

**Comment by RetroEggy** [comment]
Similar issue with the Blackwido X Chroma, Space and the FN Button can't be selected from the UI. Using a preset like static etc. works fine, however (btw congrats on the ppa, I'm so happy that pretty much everything now works with the UI).

**Comment by lah7** [comment]
@RetroEggy Similar, but not the same issue. Now that multi-device support has been implemented some time ago, it's now possible to detect keyboards and only disable <kbd>FN</kbd> and <kbd>Space</kbd> if they do not have the LEDs. This has been fixed in 763ffbcb613a56badfbff9b3320eebbd1bbbfdda (for the next update).

-----------
@hhollenstain Is the key mappings still an issue under the new daemon?

**Comment by smevawala** [comment]
I can confirm the stealth issue is still happening with the newest polychromatic.

**Comment by lah7** [comment]
I'm not entirely sure what's the issue exactly.... I'm thinking this is something at daemon level.

1. Can the keys be selected from the UI, but do not light on the keyboard?
2. **Or**, are the keys unable to be selected from the UI entirely? (Like nothing happens?)

**Comment by RetroEggy** [comment]
In my case, I'm not able to select the keys. I click space and nothing happens. Other keys work fine. When using a preset like static however, all keys including space and FN are affected.

**Comment by terrycain** [comment]
@lah7 you sure the space and fn are not disabled as I vaguely remember doing something like that

**Comment by lah7** [comment]
I think we're crossing two separate issues here.

@RetroEggy @terrycain The inability to select FN/Space has been [fixed](https://github.com/lah7/polychromatic/commit/763ffbcb613a56badfbff9b3320eebbd1bbbfdda) (a new package hasn't been pushed out yet). This can be tested by [installing the `master` version](https://github.com/lah7/polychromatic#-other-distributions--manual-installation).

The original issue description sounds like a problem with the mappings (co-ordinates?):

>  but the F1 Key, the left arrow, enter, and z keys can't be mapped from the UI. 

Which I'm assuming, when they're clicked in the editor, that key isn't lit up on the device. It could be a difference in US/UK layouts, or the wrong one is loaded in Polychromatic? Please could someone with a Razer Blade Stealth confirm if this is the problem?

**Comment by Bl4d3s** [comment]
Its a bit old this issue, but I can confirm this as well. On my razer Blade stealth an entirely wrong keyboard mapping is loaded (looks like a balckwidow layout). I can select the keys and most light up correspondingly but some do not, and some light up other keys.
Here are some screenshots:

![layout](https://user-images.githubusercontent.com/12065866/37569039-44a1f88e-2add-11e8-9a74-534760d341fc.png)
![mainwindow](https://user-images.githubusercontent.com/12065866/37569040-44d04efa-2add-11e8-8db2-7030601c695d.png)

**Comment by lah7** [comment]
Thanks for confirming @Bl4d3s. At the moment, "application profiles" are really simple and all keyboards load this SVG (graphic). In future [eventually] there will be separate SVGs that can show the correct bindings for different locale layouts / devices.

**Comment by Bl4d3s** [comment]
Okay, but still neither with the normal nor with the git version I can set all keys. Is there an easy way to fix it? I could maybe do some coding by myself if you point me in a direction.
Btw Im running Manjaro Linux

**Comment by lah7** [comment]
Should be a relatively simple DIY fix for the time being: The SVG is located at `/usr/share/polychromatic/mapping/blackwidow-chroma-keyboard-layout.svg` - You can use a vector graphics editor like **Inkscape** to change these values in the **XML Editor** window/pane:

![image](https://user-images.githubusercontent.com/13032135/37569292-12a39928-2ad8-11e8-8360-c82ac1260664.png)

There's an **onclick** that tells it what co-ordinate to set it to.

To find out the co-ordinates, I have a script in my repository that will help: **[tools/step-through-matrix.py](https://github.com/polychromatic/polychromatic/blob/master/tools/step-through-matrix.py)**

Also, when saving, Inkscape does something with the file that means it won't work in Polychromatic again without first running **[tools/svg_editor.py](https://github.com/polychromatic/polychromatic/blob/master/tools/svg_editor.py)** -- that script assumes the file is at `../data/img/blackwidow-chroma-keyboard-layout.svg`, you could tweak that path depending if you `git clone` this repo or edit it directly at `/usr/share/...`

Hopefully that should be a pointer in the right direction till this [`unstable`](https://github.com/polychromatic/polychromatic/tree/unstable) stuff gets finished.. :+1:

**Comment by Bl4d3s** [comment]
One further question: I tried to run your script tools/step-through-matrix.py, but I keep getting this error:
`./step-through-matrix.py 
Traceback (most recent call last):
  File "./step-through-matrix.py", line 7, in <module>
    import razer.client as rclient
ModuleNotFoundError: No module named 'razer'
`
Any idea how to fix?

**Comment by lah7** [comment]
Whoops, sorry, that should be:

    import openrazer.client as rclient

The daemon was renamed some time ago - I must have missed a spot 🤨

**Comment by jramapuram** [comment]
Any chance we can get these changes merged? Having a missing 'z', 'alt', 'fn' and 'f1' are dimly lit 'Shift" + "Enter" are super annoying on a 1060 RB 2016

**Comment by lah7** [comment]
Unfortunately not as-is, since the change will affect the SVG for all keyboards. The implementation to support per device is not there yet.

The **unstable** branch contains the future version where profiles will be remastered and will address issues like this (currently, that branch isn't ready). Please bear with me... it'll be sorted eventually!

For now, you can replace the SVG on your system with the one from the pull request.

**Comment by lah7** [comment]
Good news! Your Blade Stealth 2016 models now have their own graphic!

:gb: 
![Screenshot_20210319_183900](https://user-images.githubusercontent.com/13032135/111827942-72816080-88e2-11eb-961d-83e3660a210a.png)

🇺🇸 
![Screenshot_20210319_183926](https://user-images.githubusercontent.com/13032135/111827945-73b28d80-88e2-11eb-95d6-f3551ce4f4ad.png)
